# Generated by Django 5.0.14 on 2025-11-28 22:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consults', '0001_initial'),
        ('departments', '0002_department_department_type_department_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Consult Created'), ('ACKNOWLEDGED', 'Consult Acknowledged'), ('ASSIGNED', 'Consult Assigned'), ('REASSIGNED', 'Consult Reassigned'), ('NOTE_ADDED', 'Note Added'), ('STATUS_CHANGED', 'Status Changed'), ('ESCALATED', 'Consult Escalated'), ('COMPLETED', 'Consult Completed'), ('CANCELLED', 'Consult Cancelled'), ('SLA_WARNING', 'SLA Warning'), ('SLA_BREACH', 'SLA Breach')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='consults.consultrequest')),
            ],
            options={
                'db_table': 'consult_timeline',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['consult', 'timestamp'], name='consult_tim_consult_46f5e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consults_received', models.IntegerField(default=0)),
                ('consults_completed', models.IntegerField(default=0)),
                ('consults_escalated', models.IntegerField(default=0)),
                ('consults_pending', models.IntegerField(default=0)),
                ('consults_overdue', models.IntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(default=0.0)),
                ('sla_compliance_rate', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='departments.department')),
            ],
            options={
                'db_table': 'department_daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['department', '-date'], name='department__departm_07c290_idx')],
                'unique_together': {('department', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DoctorPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consults_assigned', models.IntegerField(default=0)),
                ('consults_completed', models.IntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(default=0.0)),
                ('sla_compliance_rate', models.FloatField(default=100.0)),
                ('notes_added', models.IntegerField(default=0)),
                ('escalations_received', models.IntegerField(default=0)),
                ('escalations_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_performance_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['doctor', '-date'], name='doctor_perf_doctor__30b589_idx'), models.Index(fields=['-date', 'sla_compliance_rate'], name='doctor_perf_date_123348_idx')],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
