# Generated by Django 5.0.14 on 2025-12-01 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for the device', max_length=255)),
                ('fcm_token', models.TextField(help_text='Firebase Cloud Messaging token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', help_text='Device platform (android or ios)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the device should receive notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user this device belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
