# Generated by Django 5.0.14 on 2025-12-05 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0003_consultnote_assigned_to_alter_consultnote_note_type'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for email reply handling', unique=True)),
                ('notification_type', models.CharField(choices=[('CONSULT_GENERATED', 'Consult Generated'), ('CONSULT_ACKNOWLEDGED', 'Consult Acknowledged'), ('NOTE_ADDED', 'Note Added'), ('CONSULT_CLOSED', 'Consult Closed'), ('SLA_BREACH', 'SLA Time Breach'), ('REASSIGNMENT', 'Reassignment'), ('ANALYTICS', 'Analytics Report')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('reply_received', models.BooleanField(default=False)),
                ('reply_received_at', models.DateTimeField(blank=True, null=True)),
                ('reply_action_taken', models.CharField(blank=True, help_text='Action taken based on email reply (e.g., ACKNOWLEDGED)', max_length=50)),
                ('consult', models.ForeignKey(blank=True, help_text='The consult this notification is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='consults.consultrequest')),
                ('recipient', models.ForeignKey(help_text='User who received this email', on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', '-sent_at'], name='email_notif_recipie_07c5c0_idx'), models.Index(fields=['consult', '-sent_at'], name='email_notif_consult_218a96_idx'), models.Index(fields=['reply_token'], name='email_notif_reply_t_4e0fbc_idx'), models.Index(fields=['notification_type', '-sent_at'], name='email_notif_notific_3143ef_idx')],
            },
        ),
    ]
