# Generated by Django 5.2.8 on 2025-11-27 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("URGENT", "Urgent"),
                            ("ROUTINE", "Routine"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "reason_for_consult",
                    models.TextField(help_text="Why is this consult being requested?"),
                ),
                (
                    "clinical_question",
                    models.TextField(
                        blank=True,
                        help_text="Specific question for the consulting team",
                    ),
                ),
                (
                    "relevant_history",
                    models.TextField(blank=True, help_text="Relevant patient history"),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, help_text="Current medications"),
                ),
                (
                    "vital_signs",
                    models.TextField(blank=True, help_text="Latest vital signs"),
                ),
                (
                    "lab_results",
                    models.TextField(blank=True, help_text="Relevant lab results"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_response_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expected time for response based on SLA",
                        null=True,
                    ),
                ),
                (
                    "is_overdue",
                    models.BooleanField(
                        default=False, help_text="Whether this consult is overdue"
                    ),
                ),
                (
                    "escalation_level",
                    models.IntegerField(
                        default=0, help_text="Number of times this has been escalated"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Doctor assigned to handle this consult",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_consults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consults",
                        to="patients.patient",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_consults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_consults",
                        to="departments.department",
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_consults",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "consult_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("PROGRESS", "Progress Note"),
                            ("RECOMMENDATION", "Recommendation"),
                            ("ASSESSMENT", "Assessment"),
                            ("PLAN", "Plan"),
                            ("FINAL", "Final Note"),
                        ],
                        default="PROGRESS",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Specific recommendations for patient care",
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, help_text="Does this require follow-up?"
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(
                        blank=True, help_text="Instructions for follow-up"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the final note that completes the consult?",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consult_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consult",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="consults.consultrequest",
                    ),
                ),
            ],
            options={
                "db_table": "consult_notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consultrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="consult_req_status_1b039b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultrequest",
            index=models.Index(
                fields=["target_department", "status"],
                name="consult_req_target__48e2f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultrequest",
            index=models.Index(
                fields=["assigned_to", "status"], name="consult_req_assigne_81eaa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultrequest",
            index=models.Index(
                fields=["urgency", "-created_at"], name="consult_req_urgency_c11836_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultrequest",
            index=models.Index(
                fields=["is_overdue", "status"], name="consult_req_is_over_cc5615_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultnote",
            index=models.Index(
                fields=["consult", "created_at"], name="consult_not_consult_fd81ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultnote",
            index=models.Index(
                fields=["author", "-created_at"], name="consult_not_author__c74cb3_idx"
            ),
        ),
    ]
