# Generated by Django 5.0.14 on 2025-11-29 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consults", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultrequest",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_consults",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultrequest",
            name="last_action_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="consultrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("IN_PROGRESS", "In Progress"),
                    ("MORE_INFO_REQUIRED", "More Information Required"),
                    ("COMPLETED", "Completed"),
                    ("CLOSED", "Closed"),
                ],
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
