# Generated by Django 5.0.14 on 2025-11-29 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consults", "0002_consultrequest_acknowledged_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultnote",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User this note is assigning the consult to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignment_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consultnote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("PROGRESS_UPDATE", "Progress Update"),
                    ("PLAN_MANAGEMENT", "Plan / Management"),
                    ("REQUEST_MORE_INFO", "Request More Information"),
                    ("ASSIGNED_TO", "Assigned To"),
                    ("FOLLOW_UP_NEEDED", "Follow-up Needed"),
                    ("CLOSE_CONSULT", "Close Consult"),
                ],
                default="PROGRESS_UPDATE",
                max_length=20,
            ),
        ),
    ]
