# Generated by Django 5.0.14 on 2025-12-10 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0003_consultnote_assigned_to_alter_consultnote_note_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the consult was assigned', null=True),
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this consult', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consults_assigned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='assignment_type',
            field=models.CharField(choices=[('manual', 'Manual Assignment'), ('auto', 'Auto Assignment')], default='manual', help_text='How the consult was assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When the consult was received/acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='consultrequest',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='User who received/acknowledged this consult', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consults_received_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultrequest',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use received_by instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_consults', to=settings.AUTH_USER_MODEL),
        ),
    ]
