# Generated by Django 5.0.14 on 2025-11-28 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consults', '0001_initial'),
        ('departments', '0002_department_department_type_department_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedConsultPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_threshold_percent', models.IntegerField(default=75, help_text='Percentage of SLA time at which to show warning')),
                ('escalation_levels', models.JSONField(default=list, help_text='List of escalation levels with time thresholds')),
                ('auto_escalate', models.BooleanField(default=True, help_text='Automatically escalate when threshold is reached')),
                ('notify_requester', models.BooleanField(default=True, help_text='Notify requester when consult is delayed')),
                ('notify_hod', models.BooleanField(default=True, help_text='Notify HOD when consult is delayed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_policies', to='departments.department')),
            ],
            options={
                'db_table': 'delayed_consult_policies',
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('URGENT', 'Urgent'), ('ROUTINE', 'Routine')], max_length=20)),
                ('assignment_mode', models.CharField(choices=[('ROUND_ROBIN', 'Round Robin'), ('LOAD_BALANCE', 'Load Balance'), ('SENIORITY', 'By Seniority'), ('ON_CALL', 'On-Call Only'), ('MANUAL', 'Manual Assignment')], default='MANUAL', max_length=20)),
                ('min_seniority', models.IntegerField(default=1, help_text='Minimum seniority level for auto-assignment')),
                ('escalation_minutes', models.IntegerField(default=60, help_text='Minutes before escalating to senior')),
                ('notify_hod', models.BooleanField(default=False, help_text='Notify HOD on new assignment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_policies', to='departments.department')),
            ],
            options={
                'db_table': 'assignment_policies',
                'ordering': ['department', 'urgency'],
                'unique_together': {('department', 'urgency')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONSULT_CREATED', 'Consult Created'), ('CONSULT_VIEWED', 'Consult Viewed'), ('CONSULT_ACKNOWLEDGED', 'Consult Acknowledged'), ('CONSULT_ASSIGNED', 'Consult Assigned'), ('CONSULT_REASSIGNED', 'Consult Reassigned'), ('CONSULT_STATUS_CHANGED', 'Consult Status Changed'), ('CONSULT_COMPLETED', 'Consult Completed'), ('CONSULT_CANCELLED', 'Consult Cancelled'), ('CONSULT_ESCALATED', 'Consult Escalated'), ('NOTE_ADDED', 'Note Added'), ('NOTE_UPDATED', 'Note Updated'), ('AUTO_ASSIGNED', 'Auto-Assigned'), ('LOAD_BALANCE_ASSIGNED', 'Load Balance Assigned'), ('ON_CALL_ASSIGNED', 'On-Call Assigned'), ('HOD_OVERRIDE', 'HOD Override'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('DEPARTMENT_CREATED', 'Department Created'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('PERMISSION_CHANGED', 'Permission Changed')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='consults.consultrequest')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='departments.department')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_logs_actor_i_9ecce2_idx'), models.Index(fields=['consult', '-timestamp'], name='audit_logs_consult_e52ab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'filter_presets',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_call_schedules', to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_call_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'on_call_schedules',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['department', 'is_active', 'start_time'], name='on_call_sch_departm_3feb37_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnauthorizedAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('CONSULT', 'Consult'), ('USER', 'User'), ('DEPARTMENT', 'Department'), ('DASHBOARD', 'Dashboard'), ('ADMIN', 'Admin Panel')], max_length=20)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_attempted', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unauthorized_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unauthorized_access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='unauthorize_user_id_15a272_idx'), models.Index(fields=['resource_type', '-timestamp'], name='unauthorize_resourc_39a6bf_idx')],
            },
        ),
    ]
