# Generated by Django 5.0.14 on 2025-12-05 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('departments', '0004_department_delay_action_department_max_response_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unauthorizedaccesslog',
            name='user',
        ),
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_consult_generated', models.BooleanField(default=True, help_text='Send email when a new consult is generated for this department')),
                ('notify_on_consult_acknowledged', models.BooleanField(default=True, help_text='Send email when a consult is acknowledged')),
                ('notify_on_note_added', models.BooleanField(default=True, help_text='Send email when a note is added to a consult')),
                ('notify_on_consult_closed', models.BooleanField(default=True, help_text='Send email when a consult is closed')),
                ('notify_on_sla_breach', models.BooleanField(default=True, help_text='Send email when SLA time is breached')),
                ('notify_on_reassignment', models.BooleanField(default=True, help_text='Send email when a consult is reassigned')),
                ('send_to_hod', models.BooleanField(default=True, help_text='Send notifications to Head of Department')),
                ('send_to_assigned_doctor', models.BooleanField(default=True, help_text='Send notifications to assigned doctor')),
                ('send_to_requester', models.BooleanField(default=True, help_text='Send notifications to the requester')),
                ('additional_recipients', models.TextField(blank=True, help_text='Additional email recipients (one per line)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(help_text='Department these settings apply to', on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_settings', to='departments.department')),
            ],
            options={
                'verbose_name': 'Email Notification Settings',
                'verbose_name_plural': 'Email Notification Settings',
                'db_table': 'email_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name (e.g., "Google Workspace Production")', max_length=100)),
                ('host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('username', models.CharField(help_text='SMTP username (email address)', max_length=255)),
                ('password', models.CharField(help_text='SMTP password (app password for Google)', max_length=255)),
                ('from_email', models.EmailField(help_text='Default "from" email address', max_length=254)),
                ('from_name', models.CharField(default='PMC Consult System', help_text='Default "from" name', max_length=255)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Reply-to email address (for email replies)', max_length=254)),
                ('is_active', models.BooleanField(default=False, help_text='Is this configuration currently active?')),
                ('is_test_mode', models.BooleanField(default=False, help_text='Test mode - emails will be logged but not sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_smtp_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
                'db_table': 'smtp_configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DelayedConsultPolicy',
        ),
        migrations.DeleteModel(
            name='UnauthorizedAccessLog',
        ),
    ]
