# Generated by Django 5.0 on 2025-11-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mrn",
                    models.CharField(
                        help_text="Medical Record Number", max_length=50, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                    ),
                ),
                ("ward", models.CharField(max_length=100)),
                ("bed_number", models.CharField(max_length=20)),
                ("primary_diagnosis", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["mrn"], name="patients_mrn_5d1fc1_idx"),
                    models.Index(
                        fields=["primary_department", "-created_at"],
                        name="patients_primary_f39fc5_idx",
                    ),
                ],
            },
        ),
    ]
