# Generated by Django 5.0 on 2025-11-26 09:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Doctor"),
                            ("DEPARTMENT_USER", "Department User"),
                            ("HOD", "Head of Department"),
                            ("ADMIN", "Administrator"),
                        ],
                        default="DOCTOR",
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESIDENT_1", "Resident 1"),
                            ("RESIDENT_2", "Resident 2"),
                            ("RESIDENT_3", "Resident 3"),
                            ("RESIDENT_4", "Resident 4"),
                            ("RESIDENT_5", "Resident 5"),
                            ("SENIOR_REGISTRAR", "Senior Registrar"),
                            ("ASSISTANT_PROFESSOR", "Assistant Professor"),
                            ("PROFESSOR", "Professor"),
                            ("HOD", "Head of Department"),
                        ],
                        help_text="Medical designation/rank",
                        max_length=50,
                    ),
                ),
                (
                    "seniority_level",
                    models.IntegerField(
                        default=1,
                        help_text="Auto-calculated from designation for escalation hierarchy",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "profile_photo",
                    models.URLField(blank=True, help_text="Photo from Google OAuth"),
                ),
                ("is_on_call", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
