# Generated by Django 5.0 on 2025-11-27 00:44
# Fixed: Removed invalid RemoveIndex operations for indexes that were never created
# The indexes users_email_4b85f2_idx, users_departm_6a50ab_idx, users_designa_2a55ef_idx
# were never created in migrations 0001 or 0002, so RemoveIndex operations fail.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    # Empty operations - the indexes this migration tried to remove never existed
    operations = []
