# Generated by Django 5.0 on 2025-11-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_email_4b85f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_departm_6a50ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_designa_2a55ef_idx",
        ),
    ]
