# Generated by Django 5.0.14 on 2025-11-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_consults_globally',
            field=models.BooleanField(default=False, help_text='Can reassign and manage consults across all departments'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_departments',
            field=models.BooleanField(default=False, help_text='Can create, edit, and manage departments in the Admin Panel'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_permissions',
            field=models.BooleanField(default=False, help_text='Can modify admin permission flags for other users (SuperAdmin only)'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Can create, edit, and manage users in the Admin Panel'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_department_dashboard',
            field=models.BooleanField(default=False, help_text='Can view department-level dashboards and analytics'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_global_dashboard',
            field=models.BooleanField(default=False, help_text='Can view global dashboards across all departments'),
        ),
    ]
