# Generated by Django 5.0.14 on 2025-11-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_can_manage_consults_globally_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_manage_consults_in_department",
            field=models.BooleanField(
                default=False,
                help_text="Can reassign and manage consults within their own department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_manage_consults_globally",
            field=models.BooleanField(
                default=False,
                help_text="Can reassign and manage consults across all departments (SuperAdmin only)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DOCTOR", "Doctor"),
                    ("DEPARTMENT_USER", "Department User"),
                    ("HOD", "Head of Department"),
                    ("ADMIN", "Administrator"),
                    ("SUPER_ADMIN", "Super Administrator"),
                ],
                default="DOCTOR",
                max_length=20,
            ),
        ),
    ]
