# Generated by Django 5.0.14 on 2025-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_can_manage_consults_in_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hierarchy_number",
            field=models.IntegerField(
                default=99,
                help_text="A number to define the user position in the department hierarchy",
            ),
        ),
    ]
