# Generated by Django 5.2.8 on 2025-11-27 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., CARDIO)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "emergency_sla",
                    models.IntegerField(
                        default=60, help_text="SLA for emergency consults (minutes)"
                    ),
                ),
                (
                    "urgent_sla",
                    models.IntegerField(
                        default=240, help_text="SLA for urgent consults (minutes)"
                    ),
                ),
                (
                    "routine_sla",
                    models.IntegerField(
                        default=1380, help_text="SLA for routine consults (minutes)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "HOD"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
    ]
