# Generated by Django 5.0.14 on 2025-11-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('CLINICAL', 'Clinical'), ('ADMINISTRATIVE', 'Administrative'), ('SUPPORT', 'Support')], default='CLINICAL', help_text='Type of department', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent department for sub-department hierarchy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdepartments', to='departments.department'),
        ),
    ]
