# Generated by Django 5.0.14 on 2025-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_oncall"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="delay_action",
            field=models.CharField(
                choices=[
                    ("NOTIFY_HOD", "Notify HOD"),
                    ("ESCALATE", "Escalate to Senior"),
                    ("AUTO_ASSIGN", "Auto-assign"),
                    ("MARK_OVERDUE", "Mark as Overdue"),
                ],
                default="MARK_OVERDUE",
                help_text="Action to take when a consult is delayed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="max_response_time",
            field=models.IntegerField(
                default=30,
                help_text="Maximum allowed time in minutes to acknowledge a consult",
            ),
        ),
    ]
