# Generated by Django 5.0.14 on 2025-12-10 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_delay_action_department_max_response_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='delegated_receiver',
            field=models.ForeignKey(blank=True, help_text='Senior doctor delegated to receive and assign consults', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
